create and configure database for services-devel-deps
building hoot-services requires a hoot db instance

diff --git a/src/SPECS/hootenanny.spec.in b/src/SPECS/hootenanny.spec.in
--- a/src/SPECS/hootenanny.spec.in
+++ b/src/SPECS/hootenanny.spec.in
@@ -192,9 +192,6 @@ if [ "$1" = "1" ]; then
         sudo -u postgres psql -d hoot -c 'create extension hstore;'
         sudo -u postgres psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='wfsstoredb'"
         sudo -u postgres psql -d wfsstoredb -c 'create extension postgis;'
-        sudo -u postgres psql -d wfsstoredb -c "GRANT ALL on geometry_columns TO PUBLIC;"
-        sudo -u postgres psql -d wfsstoredb -c "GRANT ALL on geography_columns TO PUBLIC;"
-        sudo -u postgres psql -d wfsstoredb -c "GRANT ALL on spatial_ref_sys TO PUBLIC;"
     fi
 
     # configure Postgres settings
@@ -472,6 +469,97 @@ This packages contains the dependencies to build and develop the Hootenanny
 services. Use this if you want to build and test from github.
 
 %files services-devel-deps
+
+%post services-ui
+if [ "$1" = "1" ]; then
+    # Perform tasks to prepare for the initial installation
+
+    # init and start Postgres
+    PG_SERVICE=$(ls /etc/init.d | grep postgresql-)
+    sudo service $PG_SERVICE initdb
+    sudo service $PG_SERVICE start
+    PG_VERSION=$(sudo -u postgres psql -c 'SHOW SERVER_VERSION;' | egrep -o '[0-9]{1,}\.[0-9]{1,}')
+
+    sudo service tomcat6 start
+
+    # create Hoot services db
+    if ! sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw hoot; then
+        RAND_PW=$(pwgen -s 16 1)
+        sudo -u postgres createuser --superuser hoot || true
+        sudo -u postgres psql -c "alter user hoot with password 'hoottest';"
+        sudo -u postgres createdb hoot --owner=hoot
+        sudo -u postgres createdb wfsstoredb --owner=hoot
+        sudo -u postgres psql -d hoot -c 'create extension hstore;'
+        sudo -u postgres psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='wfsstoredb'"
+        sudo -u postgres psql -d wfsstoredb -c 'create extension postgis;'
+    fi
+
+    # configure Postgres settings
+    PG_HB_CONF=/var/lib/pgsql/$PG_VERSION/data/pg_hba.conf
+    if ! sudo grep -i --quiet hoot $PG_HB_CONF; then
+        sudo -u postgres cp $PG_HB_CONF $PG_HB_CONF.orig
+        sudo -u postgres sed -i '1ihost    all            hoot            127.0.0.1/32            md5' $PG_HB_CONF
+        sudo -u postgres sed -i '1ihost    all            hoot            ::1/128                 md5' $PG_HB_CONF
+    fi
+    POSTGRES_CONF=/var/lib/pgsql/$PG_VERSION/data/postgresql.conf
+    if ! grep -i --quiet HOOT $POSTGRES_CONF; then
+        sudo -u postgres cp $POSTGRES_CONF $POSTGRES_CONF.orig
+        sudo -u postgres sed -i s/^max_connections/\#max_connections/ $POSTGRES_CONF
+        sudo -u postgres sed -i s/^shared_buffers/\#shared_buffers/ $POSTGRES_CONF
+        sudo -u postgres bash -c "cat >> $POSTGRES_CONF" <<EOT
+#--------------
+# Hoot Settings
+#--------------
+max_connections = 1000
+shared_buffers = 1024MB
+max_files_per_process = 1000
+work_mem = 16MB
+maintenance_work_mem = 256MB
+checkpoint_segments = 20
+autovacuum = off
+EOT
+    fi
+    # configure kernel parameters
+    SYSCTL_CONF=/etc/sysctl.conf
+    if ! grep --quiet 1173741824 $SYSCTL_CONF; then
+        sudo cp $SYSCTL_CONF $SYSCTL_CONF.orig
+        echo "Setting kernel.shmmax"
+        sudo sysctl -w kernel.shmmax=1173741824
+        sudo sh -c "echo 'kernel.shmmax=1173741824' >> $SYSCTL_CONF"
+        #                 kernel.shmmax=68719476736
+    fi
+    if ! grep --quiet 2097152 $SYSCTL_CONF; then
+        echo "Setting kernel.shmall"
+        sudo sysctl -w kernel.shmall=2097152
+        sudo sh -c "echo 'kernel.shmall=2097152' >> $SYSCTL_CONF"
+        #                 kernel.shmall=4294967296
+    fi
+    sudo service postgresql-$PG_VERSION restart
+fi
+
+%postun services-ui
+if [ "$1" = "0" ]; then
+    # Perform tasks to clean up after uninstallation
+
+    # Ensure Postgres is started
+    PG_SERVICE=$(ls /etc/init.d | grep postgresql-)
+    sudo service $PG_SERVICE start
+    PG_VERSION=$(sudo -u postgres psql -c 'SHOW SERVER_VERSION;' | egrep -o '[0-9]{1,}\.[0-9]{1,}')
+
+    # Restore Postgres settings
+    PG_HB_CONF=/var/lib/pgsql/$PG_VERSION/data/pg_hba.conf
+    if sudo grep -i --quiet hoot $PG_HB_CONF; then
+        sudo -u postgres mv $PG_HB_CONF.orig $PG_HB_CONF
+    fi
+    POSTGRES_CONF=/var/lib/pgsql/$PG_VERSION/data/postgresql.conf
+    if grep -i --quiet HOOT $POSTGRES_CONF; then
+        sudo -u postgres mv $POSTGRES_CONF.orig $POSTGRES_CONF
+    fi
+    # Restore kernal parameters
+    if sysctl -e kernel.shmmax | grep --quiet 1173741824; then
+        sudo mv /etc/sysctl.conf.orig /etc/sysctl.conf
+    fi
+fi
 
 %package core-devel-deps
 Summary:    Development dependencies for Hootenanny Core
